/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswing;

/**
 *
 * @author SAYA
 */
public class j4 extends javax.swing.JFrame {

    /**
     * Creates new form j4
     */
    public j4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabj4 = new javax.swing.JTable();
        jRDenvL = new javax.swing.JRadioButton();
        jRDpreBoxS = new javax.swing.JRadioButton();
        jRDpreBoxM = new javax.swing.JRadioButton();
        jRDpreBoxL = new javax.swing.JRadioButton();
        jButSubmit2 = new javax.swing.JButton();
        jRDenvS = new javax.swing.JRadioButton();
        jLabenvelopeOrPrepaid = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabj4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ENVELOPE S", "280MM X 200MM", "500G"},
                {"ENVELOPE L", "380MM X 320MM", "1KG"},
                {"PREPAID BOX S", "340MMX250MMX80MM", "2KG"},
                {"PREPAID BOX M", "340MMX250MMX150MM", "5KG"},
                {"PREPAID BOX L", "380MMX320MMX200MM", "10KG"}
            },
            new String [] {
                "TYPES", "SIZE", "WEIGHT MAX"
            }
        ));
        jScrollPane1.setViewportView(jTabj4);

        jRDenvL.setText("ENVELOPE M");

        jRDpreBoxS.setText("PREPAID BOX S");
        jRDpreBoxS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDpreBoxSActionPerformed(evt);
            }
        });

        jRDpreBoxM.setText("PREPAID BOX M");

        jRDpreBoxL.setText("PREPAID BOX L");

        jButSubmit2.setText("SUBMIT");

        jRDenvS.setText("ENVELOPE S");
        jRDenvS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDenvSActionPerformed(evt);
            }
        });

        jLabenvelopeOrPrepaid.setText("CHOOSE YOUR ENVELOPE OR PREPAID BOX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRDpreBoxL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jButSubmit2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRDenvS)
                            .addComponent(jRDpreBoxS)
                            .addComponent(jRDpreBoxM)
                            .addComponent(jRDenvL))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabenvelopeOrPrepaid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabenvelopeOrPrepaid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRDenvS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButSubmit2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRDenvL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRDpreBoxS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRDpreBoxM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRDpreBoxL)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(172, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRDpreBoxSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDpreBoxSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRDpreBoxSActionPerformed

    private void jRDenvSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDenvSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRDenvSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButSubmit2;
    private javax.swing.JLabel jLabenvelopeOrPrepaid;
    private javax.swing.JRadioButton jRDenvL;
    private javax.swing.JRadioButton jRDenvS;
    private javax.swing.JRadioButton jRDpreBoxL;
    private javax.swing.JRadioButton jRDpreBoxM;
    private javax.swing.JRadioButton jRDpreBoxS;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabj4;
    // End of variables declaration//GEN-END:variables
}
